### ISSUE TITLE
NoClassDefFoundError with latest mcMMO builds in 1.13

### ISSUE THREAD

**Issue by RednedEpic** [FlyingPikachu/Quests#684]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests: 3.6.1-b640 
Server: Paper version git-Paper-514 (MC:1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Loading a quest in verions 1.13+ (involving mcMMO in some way) with the latest mcMMO build throws a NoClassDefFoundError and causes any quests created after it to not load.
https://pastebin.com/2V8CdBw8

From what I can see, mcMMO changed or moved a class which caused this error to be thrown. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/8UjDzAHQ

**Comment by FlyingPikachu** [comment]
Thanks for the report. What version of mcMMO did you use to test this?

**Comment by RednedEpic** [comment]
I apologize for wasting you time; as I was looking at the version I had installed, I realized I did not have an official mcMMO version. The build I downloaded was from another developer apparently. It was the first result that popped up on my screen and I had just assumed it was the official one.

Please feel free to close this. If you are interested however, here is the link I got mcMMO from.
https://popicraft.net/jenkins/job/mcMMO/
